mkdir -p src/altq
cp ../../../../altq/altq.h src/altq/altq.h
cp ../../../../altq/altq_cbq.c src/altq/altq_cbq.c
cp ../../../../altq/altq_cbq.h src/altq/altq_cbq.h
cp ../../../../altq/altq_classq.h src/altq/altq_classq.h
cp ../../../../altq/altq_hfsc.c src/altq/altq_hfsc.c
cp ../../../../altq/altq_hfsc.h src/altq/altq_hfsc.h
cp ../../../../altq/altq_priq.c src/altq/altq_priq.c
cp ../../../../altq/altq_priq.h src/altq/altq_priq.h
cp ../../../../altq/altq_red.c src/altq/altq_red.c
cp ../../../../altq/altq_red.h src/altq/altq_red.h
cp ../../../../altq/altq_rio.h src/altq/altq_rio.h
cp ../../../../altq/altq_rmclass.c src/altq/altq_rmclass.c
cp ../../../../altq/altq_rmclass.h src/altq/altq_rmclass.h
cp ../../../../altq/altq_rmclass_debug.h src/altq/altq_rmclass_debug.h
cp ../../../../altq/altq_subr.c src/altq/altq_subr.c
cp ../../../../altq/altq_var.h src/altq/altq_var.h
cp ../../../../altq/if_altq.h src/altq/if_altq.h
mkdir -p src/arch/loongson/dev
cp ../../../../arch/loongson/dev/bonito.c src/arch/loongson/dev/bonito.c
cp ../../../../arch/loongson/dev/bonitoreg.h src/arch/loongson/dev/bonitoreg.h
cp ../../../../arch/loongson/dev/bonitovar.h src/arch/loongson/dev/bonitovar.h
cp ../../../../arch/loongson/dev/glx.c src/arch/loongson/dev/glx.c
cp ../../../../arch/loongson/dev/glxpcib.c src/arch/loongson/dev/glxpcib.c
cp ../../../../arch/loongson/dev/glxreg.h src/arch/loongson/dev/glxreg.h
cp ../../../../arch/loongson/dev/glxvar.h src/arch/loongson/dev/glxvar.h
cp ../../../../arch/loongson/dev/lemote_irq.h src/arch/loongson/dev/lemote_irq.h
cp ../../../../arch/loongson/dev/mainbus.c src/arch/loongson/dev/mainbus.c
cp ../../../../arch/loongson/dev/mcclock.c src/arch/loongson/dev/mcclock.c
cp ../../../../arch/loongson/dev/mcclock_isa.c src/arch/loongson/dev/mcclock_isa.c
cp ../../../../arch/loongson/dev/mcclockvar.h src/arch/loongson/dev/mcclockvar.h
cp ../../../../arch/loongson/dev/pcib.c src/arch/loongson/dev/pcib.c
cp ../../../../arch/loongson/dev/smfb.c src/arch/loongson/dev/smfb.c
cp ../../../../arch/loongson/dev/smfbreg.h src/arch/loongson/dev/smfbreg.h
mkdir -p src/arch/loongson/loongson
cp ../../../../arch/loongson/loongson/autoconf.c src/arch/loongson/loongson/autoconf.c
cp ../../../../arch/loongson/loongson/bus_dma.c src/arch/loongson/loongson/bus_dma.c
cp ../../../../arch/loongson/loongson/bus_space.c src/arch/loongson/loongson/bus_space.c
cp ../../../../arch/loongson/loongson/conf.c src/arch/loongson/loongson/conf.c
cp ../../../../arch/loongson/loongson/disksubr.c src/arch/loongson/loongson/disksubr.c
cp ../../../../arch/loongson/loongson/locore.S src/arch/loongson/loongson/locore.S
cp ../../../../arch/loongson/loongson/loongson2_machdep.c src/arch/loongson/loongson/loongson2_machdep.c
cp ../../../../arch/loongson/loongson/machdep.c src/arch/loongson/loongson/machdep.c
cp ../../../../arch/loongson/loongson/mutex.c src/arch/loongson/loongson/mutex.c
cp ../../../../arch/loongson/loongson/pciide_machdep.c src/arch/loongson/loongson/pciide_machdep.c
cp ../../../../arch/loongson/loongson/pmon.c src/arch/loongson/loongson/pmon.c
cp ../../../../arch/loongson/loongson/pmon32.S src/arch/loongson/loongson/pmon32.S
cp ../../../../arch/loongson/loongson/wscons_machdep.c src/arch/loongson/loongson/wscons_machdep.c
mkdir -p src/arch/mips64/dev
cp ../../../../arch/mips64/dev/clockvar.h src/arch/mips64/dev/clockvar.h
mkdir -p src/arch/mips64/mips64
cp ../../../../arch/mips64/mips64/cache_loongson2.S src/arch/mips64/mips64/cache_loongson2.S
cp ../../../../arch/mips64/mips64/clock.c src/arch/mips64/mips64/clock.c
cp ../../../../arch/mips64/mips64/context.S src/arch/mips64/mips64/context.S
cp ../../../../arch/mips64/mips64/cp0access.S src/arch/mips64/mips64/cp0access.S
cp ../../../../arch/mips64/mips64/cpu.c src/arch/mips64/mips64/cpu.c
cp ../../../../arch/mips64/mips64/db_disasm.c src/arch/mips64/mips64/db_disasm.c
cp ../../../../arch/mips64/mips64/db_machdep.c src/arch/mips64/mips64/db_machdep.c
cp ../../../../arch/mips64/mips64/exception.S src/arch/mips64/mips64/exception.S
cp ../../../../arch/mips64/mips64/fp.S src/arch/mips64/mips64/fp.S
cp ../../../../arch/mips64/mips64/interrupt.c src/arch/mips64/mips64/interrupt.c
cp ../../../../arch/mips64/mips64/lcore_access.S src/arch/mips64/mips64/lcore_access.S
cp ../../../../arch/mips64/mips64/lcore_ddb.S src/arch/mips64/mips64/lcore_ddb.S
cp ../../../../arch/mips64/mips64/lcore_float.S src/arch/mips64/mips64/lcore_float.S
cp ../../../../arch/mips64/mips64/mem.c src/arch/mips64/mips64/mem.c
cp ../../../../arch/mips64/mips64/pmap.c src/arch/mips64/mips64/pmap.c
cp ../../../../arch/mips64/mips64/process_machdep.c src/arch/mips64/mips64/process_machdep.c
cp ../../../../arch/mips64/mips64/sendsig.c src/arch/mips64/mips64/sendsig.c
cp ../../../../arch/mips64/mips64/softintr.c src/arch/mips64/mips64/softintr.c
cp ../../../../arch/mips64/mips64/sys_machdep.c src/arch/mips64/mips64/sys_machdep.c
cp ../../../../arch/mips64/mips64/tlbhandler.S src/arch/mips64/mips64/tlbhandler.S
cp ../../../../arch/mips64/mips64/trap.c src/arch/mips64/mips64/trap.c
cp ../../../../arch/mips64/mips64/vm_machdep.c src/arch/mips64/mips64/vm_machdep.c
mkdir -p src/compat/common
cp ../../../../compat/common/compat_dir.c src/compat/common/compat_dir.c
cp ../../../../compat/common/compat_dir.h src/compat/common/compat_dir.h
cp ../../../../compat/common/compat_exec.c src/compat/common/compat_exec.c
cp ../../../../compat/common/compat_util.c src/compat/common/compat_util.c
cp ../../../../compat/common/compat_util.h src/compat/common/compat_util.h
cp ../../../../compat/common/kern_exit_43.c src/compat/common/kern_exit_43.c
cp ../../../../compat/common/kern_info_43.c src/compat/common/kern_info_43.c
cp ../../../../compat/common/kern_resource_43.c src/compat/common/kern_resource_43.c
cp ../../../../compat/common/kern_sig_43.c src/compat/common/kern_sig_43.c
cp ../../../../compat/common/tty_43.c src/compat/common/tty_43.c
cp ../../../../compat/common/uipc_syscalls_43.c src/compat/common/uipc_syscalls_43.c
cp ../../../../compat/common/vfs_syscalls_43.c src/compat/common/vfs_syscalls_43.c
cp ../../../../compat/common/vfs_syscalls_o43.c src/compat/common/vfs_syscalls_o43.c
cp ../../../../compat/common/vm_43.c src/compat/common/vm_43.c
mkdir -p src/conf
cp ../../../../conf/swapgeneric.c src/conf/swapgeneric.c
mkdir -p src/crypto
cp ../../../../crypto/arc4.c src/crypto/arc4.c
cp ../../../../crypto/arc4.h src/crypto/arc4.h
cp ../../../../crypto/blf.c src/crypto/blf.c
cp ../../../../crypto/blf.h src/crypto/blf.h
cp ../../../../crypto/cast.c src/crypto/cast.c
cp ../../../../crypto/cast.h src/crypto/cast.h
cp ../../../../crypto/castsb.h src/crypto/castsb.h
cp ../../../../crypto/cmac.c src/crypto/cmac.c
cp ../../../../crypto/cmac.h src/crypto/cmac.h
cp ../../../../crypto/criov.c src/crypto/criov.c
cp ../../../../crypto/crypto.c src/crypto/crypto.c
cp ../../../../crypto/cryptodev.c src/crypto/cryptodev.c
cp ../../../../crypto/cryptodev.h src/crypto/cryptodev.h
cp ../../../../crypto/cryptosoft.c src/crypto/cryptosoft.c
cp ../../../../crypto/cryptosoft.h src/crypto/cryptosoft.h
cp ../../../../crypto/deflate.c src/crypto/deflate.c
cp ../../../../crypto/deflate.h src/crypto/deflate.h
cp ../../../../crypto/des.h src/crypto/des.h
cp ../../../../crypto/des_locl.h src/crypto/des_locl.h
cp ../../../../crypto/ecb3_enc.c src/crypto/ecb3_enc.c
cp ../../../../crypto/ecb_enc.c src/crypto/ecb_enc.c
cp ../../../../crypto/hmac.c src/crypto/hmac.c
cp ../../../../crypto/hmac.h src/crypto/hmac.h
cp ../../../../crypto/idgen.c src/crypto/idgen.c
cp ../../../../crypto/idgen.h src/crypto/idgen.h
cp ../../../../crypto/key_wrap.c src/crypto/key_wrap.c
cp ../../../../crypto/key_wrap.h src/crypto/key_wrap.h
cp ../../../../crypto/md5.c src/crypto/md5.c
cp ../../../../crypto/md5.h src/crypto/md5.h
cp ../../../../crypto/michael.c src/crypto/michael.c
cp ../../../../crypto/michael.h src/crypto/michael.h
cp ../../../../crypto/podd.h src/crypto/podd.h
cp ../../../../crypto/rijndael.c src/crypto/rijndael.c
cp ../../../../crypto/rijndael.h src/crypto/rijndael.h
cp ../../../../crypto/rmd160.c src/crypto/rmd160.c
cp ../../../../crypto/rmd160.h src/crypto/rmd160.h
cp ../../../../crypto/set_key.c src/crypto/set_key.c
cp ../../../../crypto/sha1.c src/crypto/sha1.c
cp ../../../../crypto/sha1.h src/crypto/sha1.h
cp ../../../../crypto/sha2.c src/crypto/sha2.c
cp ../../../../crypto/sha2.h src/crypto/sha2.h
cp ../../../../crypto/sk.h src/crypto/sk.h
cp ../../../../crypto/skipjack.c src/crypto/skipjack.c
cp ../../../../crypto/skipjack.h src/crypto/skipjack.h
cp ../../../../crypto/spr.h src/crypto/spr.h
cp ../../../../crypto/xform.c src/crypto/xform.c
cp ../../../../crypto/xform.h src/crypto/xform.h
mkdir -p src/ddb
cp ../../../../ddb/db_access.c src/ddb/db_access.c
cp ../../../../ddb/db_access.h src/ddb/db_access.h
cp ../../../../ddb/db_aout.c src/ddb/db_aout.c
cp ../../../../ddb/db_break.c src/ddb/db_break.c
cp ../../../../ddb/db_break.h src/ddb/db_break.h
cp ../../../../ddb/db_command.c src/ddb/db_command.c
cp ../../../../ddb/db_command.h src/ddb/db_command.h
cp ../../../../ddb/db_elf.c src/ddb/db_elf.c
cp ../../../../ddb/db_examine.c src/ddb/db_examine.c
cp ../../../../ddb/db_expr.c src/ddb/db_expr.c
cp ../../../../ddb/db_extern.h src/ddb/db_extern.h
cp ../../../../ddb/db_hangman.c src/ddb/db_hangman.c
cp ../../../../ddb/db_input.c src/ddb/db_input.c
cp ../../../../ddb/db_interface.h src/ddb/db_interface.h
cp ../../../../ddb/db_lex.c src/ddb/db_lex.c
cp ../../../../ddb/db_lex.h src/ddb/db_lex.h
cp ../../../../ddb/db_output.c src/ddb/db_output.c
cp ../../../../ddb/db_output.h src/ddb/db_output.h
cp ../../../../ddb/db_print.c src/ddb/db_print.c
cp ../../../../ddb/db_run.c src/ddb/db_run.c
cp ../../../../ddb/db_run.h src/ddb/db_run.h
cp ../../../../ddb/db_sym.c src/ddb/db_sym.c
cp ../../../../ddb/db_sym.h src/ddb/db_sym.h
cp ../../../../ddb/db_trap.c src/ddb/db_trap.c
cp ../../../../ddb/db_usrreq.c src/ddb/db_usrreq.c
cp ../../../../ddb/db_var.h src/ddb/db_var.h
cp ../../../../ddb/db_variables.c src/ddb/db_variables.c
cp ../../../../ddb/db_variables.h src/ddb/db_variables.h
cp ../../../../ddb/db_watch.c src/ddb/db_watch.c
cp ../../../../ddb/db_watch.h src/ddb/db_watch.h
cp ../../../../ddb/db_write_cmd.c src/ddb/db_write_cmd.c
mkdir -p src/dev/ata
cp ../../../../dev/ata/ata.c src/dev/ata/ata.c
cp ../../../../dev/ata/ata_wdc.c src/dev/ata/ata_wdc.c
cp ../../../../dev/ata/atareg.h src/dev/ata/atareg.h
cp ../../../../dev/ata/atavar.h src/dev/ata/atavar.h
cp ../../../../dev/ata/satareg.h src/dev/ata/satareg.h
cp ../../../../dev/ata/wd.c src/dev/ata/wd.c
cp ../../../../dev/ata/wdvar.h src/dev/ata/wdvar.h
mkdir -p src/dev/atapiscsi
cp ../../../../dev/atapiscsi/atapiscsi.c src/dev/atapiscsi/atapiscsi.c
mkdir -p src/dev
cp ../../../../dev/bio.c src/dev/bio.c
cp ../../../../dev/biovar.h src/dev/biovar.h
cp ../../../../dev/ccd.c src/dev/ccd.c
cp ../../../../dev/ccdvar.h src/dev/ccdvar.h
cp ../../../../dev/clock_subr.h src/dev/clock_subr.h
cp ../../../../dev/cninit.c src/dev/cninit.c
cp ../../../../dev/cons.c src/dev/cons.c
cp ../../../../dev/cons.h src/dev/cons.h
cp ../../../../dev/firmload.c src/dev/firmload.c
mkdir -p src/dev/gpio
cp ../../../../dev/gpio/gpiovar.h src/dev/gpio/gpiovar.h
mkdir -p src/dev/ic
cp ../../../../dev/ic/i8042reg.h src/dev/ic/i8042reg.h
cp ../../../../dev/ic/i8237reg.h src/dev/ic/i8237reg.h
cp ../../../../dev/ic/mc146818reg.h src/dev/ic/mc146818reg.h
cp ../../../../dev/ic/pckbc.c src/dev/ic/pckbc.c
cp ../../../../dev/ic/pckbcvar.h src/dev/ic/pckbcvar.h
cp ../../../../dev/ic/rtl81x9.c src/dev/ic/rtl81x9.c
cp ../../../../dev/ic/rtl81x9reg.h src/dev/ic/rtl81x9reg.h
cp ../../../../dev/ic/wdc.c src/dev/ic/wdc.c
cp ../../../../dev/ic/wdcevent.h src/dev/ic/wdcevent.h
cp ../../../../dev/ic/wdcreg.h src/dev/ic/wdcreg.h
cp ../../../../dev/ic/wdcvar.h src/dev/ic/wdcvar.h
mkdir -p src/dev/isa
cp ../../../../dev/isa/isa.c src/dev/isa/isa.c
cp ../../../../dev/isa/isadmareg.h src/dev/isa/isadmareg.h
cp ../../../../dev/isa/isareg.h src/dev/isa/isareg.h
cp ../../../../dev/isa/isavar.h src/dev/isa/isavar.h
cp ../../../../dev/isa/pckbc_isa.c src/dev/isa/pckbc_isa.c
cp ../../../../dev/ksyms.c src/dev/ksyms.c
mkdir -p src/dev/mii
cp ../../../../dev/mii/mii.c src/dev/mii/mii.c
cp ../../../../dev/mii/mii.h src/dev/mii/mii.h
cp ../../../../dev/mii/mii_physubr.c src/dev/mii/mii_physubr.c
cp ../../../../dev/mii/miidevs.h src/dev/mii/miidevs.h
cp ../../../../dev/mii/miivar.h src/dev/mii/miivar.h
cp ../../../../dev/mii/rlphy.c src/dev/mii/rlphy.c
cp ../../../../dev/mii/ukphy.c src/dev/mii/ukphy.c
cp ../../../../dev/mii/ukphy_subr.c src/dev/mii/ukphy_subr.c
cp ../../../../dev/mii/urlphy.c src/dev/mii/urlphy.c
cp ../../../../dev/mii/urlphyreg.h src/dev/mii/urlphyreg.h
mkdir -p src/dev/pci
cp ../../../../dev/pci/cy82c693.c src/dev/pci/cy82c693.c
cp ../../../../dev/pci/cy82c693reg.h src/dev/pci/cy82c693reg.h
cp ../../../../dev/pci/cy82c693var.h src/dev/pci/cy82c693var.h
cp ../../../../dev/pci/ehci_pci.c src/dev/pci/ehci_pci.c
cp ../../../../dev/pci/if_rl_pci.c src/dev/pci/if_rl_pci.c
cp ../../../../dev/pci/ohci_pci.c src/dev/pci/ohci_pci.c
cp ../../../../dev/pci/pci.c src/dev/pci/pci.c
cp ../../../../dev/pci/pci_map.c src/dev/pci/pci_map.c
cp ../../../../dev/pci/pci_quirks.c src/dev/pci/pci_quirks.c
cp ../../../../dev/pci/pci_subr.c src/dev/pci/pci_subr.c
cp ../../../../dev/pci/pcidevs.h src/dev/pci/pcidevs.h
cp ../../../../dev/pci/pcidevs_data.h src/dev/pci/pcidevs_data.h
cp ../../../../dev/pci/pciide.c src/dev/pci/pciide.c
cp ../../../../dev/pci/pciide_acard_reg.h src/dev/pci/pciide_acard_reg.h
cp ../../../../dev/pci/pciide_acer_reg.h src/dev/pci/pciide_acer_reg.h
cp ../../../../dev/pci/pciide_amd_reg.h src/dev/pci/pciide_amd_reg.h
cp ../../../../dev/pci/pciide_apollo_reg.h src/dev/pci/pciide_apollo_reg.h
cp ../../../../dev/pci/pciide_cmd_reg.h src/dev/pci/pciide_cmd_reg.h
cp ../../../../dev/pci/pciide_cy693_reg.h src/dev/pci/pciide_cy693_reg.h
cp ../../../../dev/pci/pciide_hpt_reg.h src/dev/pci/pciide_hpt_reg.h
cp ../../../../dev/pci/pciide_i31244_reg.h src/dev/pci/pciide_i31244_reg.h
cp ../../../../dev/pci/pciide_ite_reg.h src/dev/pci/pciide_ite_reg.h
cp ../../../../dev/pci/pciide_ixp_reg.h src/dev/pci/pciide_ixp_reg.h
cp ../../../../dev/pci/pciide_jmicron_reg.h src/dev/pci/pciide_jmicron_reg.h
cp ../../../../dev/pci/pciide_natsemi_reg.h src/dev/pci/pciide_natsemi_reg.h
cp ../../../../dev/pci/pciide_nforce_reg.h src/dev/pci/pciide_nforce_reg.h
cp ../../../../dev/pci/pciide_opti_reg.h src/dev/pci/pciide_opti_reg.h
cp ../../../../dev/pci/pciide_pdc202xx_reg.h src/dev/pci/pciide_pdc202xx_reg.h
cp ../../../../dev/pci/pciide_piix_reg.h src/dev/pci/pciide_piix_reg.h
cp ../../../../dev/pci/pciide_sii3112_reg.h src/dev/pci/pciide_sii3112_reg.h
cp ../../../../dev/pci/pciide_sis_reg.h src/dev/pci/pciide_sis_reg.h
cp ../../../../dev/pci/pciide_svwsata_reg.h src/dev/pci/pciide_svwsata_reg.h
cp ../../../../dev/pci/pciidereg.h src/dev/pci/pciidereg.h
cp ../../../../dev/pci/pciidevar.h src/dev/pci/pciidevar.h
cp ../../../../dev/pci/pcireg.h src/dev/pci/pcireg.h
cp ../../../../dev/pci/pcivar.h src/dev/pci/pcivar.h
cp ../../../../dev/pci/ppbreg.h src/dev/pci/ppbreg.h
cp ../../../../dev/pci/uhci_pci.c src/dev/pci/uhci_pci.c
mkdir -p src/dev/pckbc
cp ../../../../dev/pckbc/pckbd.c src/dev/pckbc/pckbd.c
cp ../../../../dev/pckbc/pckbdreg.h src/dev/pckbc/pckbdreg.h
cp ../../../../dev/pckbc/pckbdvar.h src/dev/pckbc/pckbdvar.h
cp ../../../../dev/pckbc/pms_intelli.c src/dev/pckbc/pms_intelli.c
cp ../../../../dev/pckbc/pmsreg.h src/dev/pckbc/pmsreg.h
cp ../../../../dev/pckbc/wskbdmap_mfii.c src/dev/pckbc/wskbdmap_mfii.c
cp ../../../../dev/pckbc/wskbdmap_mfii.h src/dev/pckbc/wskbdmap_mfii.h
mkdir -p src/dev/rasops
cp ../../../../dev/rasops/rasops.c src/dev/rasops/rasops.c
cp ../../../../dev/rasops/rasops.h src/dev/rasops/rasops.h
cp ../../../../dev/rasops/rasops15.c src/dev/rasops/rasops15.c
cp ../../../../dev/rnd.c src/dev/rnd.c
cp ../../../../dev/rndioctl.h src/dev/rndioctl.h
cp ../../../../dev/rndvar.h src/dev/rndvar.h
cp ../../../../dev/softraid.c src/dev/softraid.c
cp ../../../../dev/softraid_crypto.c src/dev/softraid_crypto.c
cp ../../../../dev/softraid_raid0.c src/dev/softraid_raid0.c
cp ../../../../dev/softraid_raid1.c src/dev/softraid_raid1.c
cp ../../../../dev/softraid_raid6.c src/dev/softraid_raid6.c
cp ../../../../dev/softraid_raidp.c src/dev/softraid_raidp.c
cp ../../../../dev/softraidvar.h src/dev/softraidvar.h
cp ../../../../dev/systrace.c src/dev/systrace.c
cp ../../../../dev/systrace.h src/dev/systrace.h
mkdir -p src/dev/usb
cp ../../../../dev/usb/ehci.c src/dev/usb/ehci.c
cp ../../../../dev/usb/ehcireg.h src/dev/usb/ehcireg.h
cp ../../../../dev/usb/ehcivar.h src/dev/usb/ehcivar.h
cp ../../../../dev/usb/hid.c src/dev/usb/hid.c
cp ../../../../dev/usb/hid.h src/dev/usb/hid.h
cp ../../../../dev/usb/if_url.c src/dev/usb/if_url.c
cp ../../../../dev/usb/if_urlreg.h src/dev/usb/if_urlreg.h
cp ../../../../dev/usb/if_urtw.c src/dev/usb/if_urtw.c
cp ../../../../dev/usb/if_urtwreg.h src/dev/usb/if_urtwreg.h
cp ../../../../dev/usb/ohci.c src/dev/usb/ohci.c
cp ../../../../dev/usb/ohcireg.h src/dev/usb/ohcireg.h
cp ../../../../dev/usb/ohcivar.h src/dev/usb/ohcivar.h
cp ../../../../dev/usb/ugraphire_rdesc.h src/dev/usb/ugraphire_rdesc.h
cp ../../../../dev/usb/uhci.c src/dev/usb/uhci.c
cp ../../../../dev/usb/uhcireg.h src/dev/usb/uhcireg.h
cp ../../../../dev/usb/uhcivar.h src/dev/usb/uhcivar.h
cp ../../../../dev/usb/uhid.c src/dev/usb/uhid.c
cp ../../../../dev/usb/uhidev.c src/dev/usb/uhidev.c
cp ../../../../dev/usb/uhidev.h src/dev/usb/uhidev.h
cp ../../../../dev/usb/uhub.c src/dev/usb/uhub.c
cp ../../../../dev/usb/ukbd.c src/dev/usb/ukbd.c
cp ../../../../dev/usb/ukbdmap.c src/dev/usb/ukbdmap.c
cp ../../../../dev/usb/ukbdvar.h src/dev/usb/ukbdvar.h
cp ../../../../dev/usb/umass.c src/dev/usb/umass.c
cp ../../../../dev/usb/umass_quirks.c src/dev/usb/umass_quirks.c
cp ../../../../dev/usb/umass_quirks.h src/dev/usb/umass_quirks.h
cp ../../../../dev/usb/umass_scsi.c src/dev/usb/umass_scsi.c
cp ../../../../dev/usb/umass_scsi.h src/dev/usb/umass_scsi.h
cp ../../../../dev/usb/umassvar.h src/dev/usb/umassvar.h
cp ../../../../dev/usb/ums.c src/dev/usb/ums.c
cp ../../../../dev/usb/usb.c src/dev/usb/usb.c
cp ../../../../dev/usb/usb.h src/dev/usb/usb.h
cp ../../../../dev/usb/usb_mem.c src/dev/usb/usb_mem.c
cp ../../../../dev/usb/usb_mem.h src/dev/usb/usb_mem.h
cp ../../../../dev/usb/usb_quirks.c src/dev/usb/usb_quirks.c
cp ../../../../dev/usb/usb_quirks.h src/dev/usb/usb_quirks.h
cp ../../../../dev/usb/usb_subr.c src/dev/usb/usb_subr.c
cp ../../../../dev/usb/usbdevs.h src/dev/usb/usbdevs.h
cp ../../../../dev/usb/usbdevs_data.h src/dev/usb/usbdevs_data.h
cp ../../../../dev/usb/usbdi.c src/dev/usb/usbdi.c
cp ../../../../dev/usb/usbdi.h src/dev/usb/usbdi.h
cp ../../../../dev/usb/usbdi_util.c src/dev/usb/usbdi_util.c
cp ../../../../dev/usb/usbdi_util.h src/dev/usb/usbdi_util.h
cp ../../../../dev/usb/usbdivar.h src/dev/usb/usbdivar.h
cp ../../../../dev/usb/usbhid.h src/dev/usb/usbhid.h
cp ../../../../dev/usb/uvideo.c src/dev/usb/uvideo.c
cp ../../../../dev/usb/uvideo.h src/dev/usb/uvideo.h
cp ../../../../dev/video.c src/dev/video.c
cp ../../../../dev/video_if.h src/dev/video_if.h
cp ../../../../dev/videovar.h src/dev/videovar.h
cp ../../../../dev/vnd.c src/dev/vnd.c
cp ../../../../dev/vndioctl.h src/dev/vndioctl.h
cp ../../../../dev/vscsi.c src/dev/vscsi.c
cp ../../../../dev/vscsivar.h src/dev/vscsivar.h
mkdir -p src/dev/wscons
cp ../../../../dev/wscons/ascii.h src/dev/wscons/ascii.h
cp ../../../../dev/wscons/unicode.h src/dev/wscons/unicode.h
cp ../../../../dev/wscons/wscons_callbacks.h src/dev/wscons/wscons_callbacks.h
cp ../../../../dev/wscons/wsconsio.h src/dev/wscons/wsconsio.h
cp ../../../../dev/wscons/wsdisplay.c src/dev/wscons/wsdisplay.c
cp ../../../../dev/wscons/wsdisplayvar.h src/dev/wscons/wsdisplayvar.h
cp ../../../../dev/wscons/wsemul_vt100.c src/dev/wscons/wsemul_vt100.c
cp ../../../../dev/wscons/wsemul_vt100_chars.c src/dev/wscons/wsemul_vt100_chars.c
cp ../../../../dev/wscons/wsemul_vt100_keys.c src/dev/wscons/wsemul_vt100_keys.c
cp ../../../../dev/wscons/wsemul_vt100_subr.c src/dev/wscons/wsemul_vt100_subr.c
cp ../../../../dev/wscons/wsemul_vt100var.h src/dev/wscons/wsemul_vt100var.h
cp ../../../../dev/wscons/wsemulconf.c src/dev/wscons/wsemulconf.c
cp ../../../../dev/wscons/wsemulvar.h src/dev/wscons/wsemulvar.h
cp ../../../../dev/wscons/wsevent.c src/dev/wscons/wsevent.c
cp ../../../../dev/wscons/wseventvar.h src/dev/wscons/wseventvar.h
cp ../../../../dev/wscons/wskbd.c src/dev/wscons/wskbd.c
cp ../../../../dev/wscons/wskbdutil.c src/dev/wscons/wskbdutil.c
cp ../../../../dev/wscons/wskbdvar.h src/dev/wscons/wskbdvar.h
cp ../../../../dev/wscons/wsksymdef.h src/dev/wscons/wsksymdef.h
cp ../../../../dev/wscons/wsksymvar.h src/dev/wscons/wsksymvar.h
cp ../../../../dev/wscons/wsmouse.c src/dev/wscons/wsmouse.c
cp ../../../../dev/wscons/wsmoused.h src/dev/wscons/wsmoused.h
cp ../../../../dev/wscons/wsmousevar.h src/dev/wscons/wsmousevar.h
cp ../../../../dev/wscons/wsmuxvar.h src/dev/wscons/wsmuxvar.h
mkdir -p src/dev/wsfont
cp ../../../../dev/wsfont/bold8x16-iso1.h src/dev/wsfont/bold8x16-iso1.h
cp ../../../../dev/wsfont/gallant12x22.h src/dev/wsfont/gallant12x22.h
cp ../../../../dev/wsfont/wsfont.c src/dev/wsfont/wsfont.c
cp ../../../../dev/wsfont/wsfont.h src/dev/wsfont/wsfont.h
mkdir -p src/isofs/cd9660
cp ../../../../isofs/cd9660/cd9660_bmap.c src/isofs/cd9660/cd9660_bmap.c
cp ../../../../isofs/cd9660/cd9660_extern.h src/isofs/cd9660/cd9660_extern.h
cp ../../../../isofs/cd9660/cd9660_lookup.c src/isofs/cd9660/cd9660_lookup.c
cp ../../../../isofs/cd9660/cd9660_node.c src/isofs/cd9660/cd9660_node.c
cp ../../../../isofs/cd9660/cd9660_node.h src/isofs/cd9660/cd9660_node.h
cp ../../../../isofs/cd9660/cd9660_rrip.c src/isofs/cd9660/cd9660_rrip.c
cp ../../../../isofs/cd9660/cd9660_rrip.h src/isofs/cd9660/cd9660_rrip.h
cp ../../../../isofs/cd9660/cd9660_util.c src/isofs/cd9660/cd9660_util.c
cp ../../../../isofs/cd9660/cd9660_vfsops.c src/isofs/cd9660/cd9660_vfsops.c
cp ../../../../isofs/cd9660/cd9660_vnops.c src/isofs/cd9660/cd9660_vnops.c
cp ../../../../isofs/cd9660/iso.h src/isofs/cd9660/iso.h
cp ../../../../isofs/cd9660/iso_rrip.h src/isofs/cd9660/iso_rrip.h
mkdir -p src/isofs/udf
cp ../../../../isofs/udf/ecma167-udf.h src/isofs/udf/ecma167-udf.h
cp ../../../../isofs/udf/udf.h src/isofs/udf/udf.h
cp ../../../../isofs/udf/udf_extern.h src/isofs/udf/udf_extern.h
cp ../../../../isofs/udf/udf_subr.c src/isofs/udf/udf_subr.c
cp ../../../../isofs/udf/udf_vfsops.c src/isofs/udf/udf_vfsops.c
cp ../../../../isofs/udf/udf_vnops.c src/isofs/udf/udf_vnops.c
mkdir -p src/kern
cp ../../../../kern/clock_subr.c src/kern/clock_subr.c
cp ../../../../kern/exec_aout.c src/kern/exec_aout.c
cp ../../../../kern/exec_conf.c src/kern/exec_conf.c
cp ../../../../kern/exec_ecoff.c src/kern/exec_ecoff.c
cp ../../../../kern/exec_elf.c src/kern/exec_elf.c
cp ../../../../kern/exec_elf32.c src/kern/exec_elf32.c
cp ../../../../kern/exec_elf64.c src/kern/exec_elf64.c
cp ../../../../kern/exec_script.c src/kern/exec_script.c
cp ../../../../kern/exec_subr.c src/kern/exec_subr.c
cp ../../../../kern/init_main.c src/kern/init_main.c
cp ../../../../kern/init_sysent.c src/kern/init_sysent.c
cp ../../../../kern/kern_acct.c src/kern/kern_acct.c
cp ../../../../kern/kern_clock.c src/kern/kern_clock.c
cp ../../../../kern/kern_descrip.c src/kern/kern_descrip.c
cp ../../../../kern/kern_event.c src/kern/kern_event.c
cp ../../../../kern/kern_exec.c src/kern/kern_exec.c
cp ../../../../kern/kern_exit.c src/kern/kern_exit.c
cp ../../../../kern/kern_fork.c src/kern/kern_fork.c
cp ../../../../kern/kern_kthread.c src/kern/kern_kthread.c
cp ../../../../kern/kern_ktrace.c src/kern/kern_ktrace.c
cp ../../../../kern/kern_lkm.c src/kern/kern_lkm.c
cp ../../../../kern/kern_lock.c src/kern/kern_lock.c
cp ../../../../kern/kern_malloc.c src/kern/kern_malloc.c
cp ../../../../kern/kern_physio.c src/kern/kern_physio.c
cp ../../../../kern/kern_proc.c src/kern/kern_proc.c
cp ../../../../kern/kern_prot.c src/kern/kern_prot.c
cp ../../../../kern/kern_resource.c src/kern/kern_resource.c
cp ../../../../kern/kern_rwlock.c src/kern/kern_rwlock.c
cp ../../../../kern/kern_sched.c src/kern/kern_sched.c
cp ../../../../kern/kern_sensors.c src/kern/kern_sensors.c
cp ../../../../kern/kern_sig.c src/kern/kern_sig.c
cp ../../../../kern/kern_subr.c src/kern/kern_subr.c
cp ../../../../kern/kern_synch.c src/kern/kern_synch.c
cp ../../../../kern/kern_sysctl.c src/kern/kern_sysctl.c
cp ../../../../kern/kern_tc.c src/kern/kern_tc.c
cp ../../../../kern/kern_time.c src/kern/kern_time.c
cp ../../../../kern/kern_timeout.c src/kern/kern_timeout.c
cp ../../../../kern/kern_watchdog.c src/kern/kern_watchdog.c
cp ../../../../kern/kern_workq.c src/kern/kern_workq.c
cp ../../../../kern/kern_xxx.c src/kern/kern_xxx.c
cp ../../../../kern/sched_bsd.c src/kern/sched_bsd.c
cp ../../../../kern/subr_autoconf.c src/kern/subr_autoconf.c
cp ../../../../kern/subr_disk.c src/kern/subr_disk.c
cp ../../../../kern/subr_evcount.c src/kern/subr_evcount.c
cp ../../../../kern/subr_extent.c src/kern/subr_extent.c
cp ../../../../kern/subr_log.c src/kern/subr_log.c
cp ../../../../kern/subr_pool.c src/kern/subr_pool.c
cp ../../../../kern/subr_prf.c src/kern/subr_prf.c
cp ../../../../kern/subr_prof.c src/kern/subr_prof.c
cp ../../../../kern/subr_userconf.c src/kern/subr_userconf.c
cp ../../../../kern/subr_xxx.c src/kern/subr_xxx.c
cp ../../../../kern/sys_generic.c src/kern/sys_generic.c
cp ../../../../kern/sys_pipe.c src/kern/sys_pipe.c
cp ../../../../kern/sys_process.c src/kern/sys_process.c
cp ../../../../kern/sys_socket.c src/kern/sys_socket.c
cp ../../../../kern/sysv_ipc.c src/kern/sysv_ipc.c
cp ../../../../kern/sysv_msg.c src/kern/sysv_msg.c
cp ../../../../kern/sysv_sem.c src/kern/sysv_sem.c
cp ../../../../kern/sysv_shm.c src/kern/sysv_shm.c
cp ../../../../kern/tty.c src/kern/tty.c
cp ../../../../kern/tty_conf.c src/kern/tty_conf.c
cp ../../../../kern/tty_endrun.c src/kern/tty_endrun.c
cp ../../../../kern/tty_msts.c src/kern/tty_msts.c
cp ../../../../kern/tty_nmea.c src/kern/tty_nmea.c
cp ../../../../kern/tty_pty.c src/kern/tty_pty.c
cp ../../../../kern/tty_subr.c src/kern/tty_subr.c
cp ../../../../kern/tty_tty.c src/kern/tty_tty.c
cp ../../../../kern/uipc_domain.c src/kern/uipc_domain.c
cp ../../../../kern/uipc_mbuf.c src/kern/uipc_mbuf.c
cp ../../../../kern/uipc_mbuf2.c src/kern/uipc_mbuf2.c
cp ../../../../kern/uipc_proto.c src/kern/uipc_proto.c
cp ../../../../kern/uipc_socket.c src/kern/uipc_socket.c
cp ../../../../kern/uipc_socket2.c src/kern/uipc_socket2.c
cp ../../../../kern/uipc_syscalls.c src/kern/uipc_syscalls.c
cp ../../../../kern/uipc_usrreq.c src/kern/uipc_usrreq.c
cp ../../../../kern/vfs_bio.c src/kern/vfs_bio.c
cp ../../../../kern/vfs_biomem.c src/kern/vfs_biomem.c
cp ../../../../kern/vfs_cache.c src/kern/vfs_cache.c
cp ../../../../kern/vfs_cluster.c src/kern/vfs_cluster.c
cp ../../../../kern/vfs_conf.c src/kern/vfs_conf.c
cp ../../../../kern/vfs_default.c src/kern/vfs_default.c
cp ../../../../kern/vfs_getcwd.c src/kern/vfs_getcwd.c
cp ../../../../kern/vfs_init.c src/kern/vfs_init.c
cp ../../../../kern/vfs_lockf.c src/kern/vfs_lockf.c
cp ../../../../kern/vfs_lookup.c src/kern/vfs_lookup.c
cp ../../../../kern/vfs_subr.c src/kern/vfs_subr.c
cp ../../../../kern/vfs_sync.c src/kern/vfs_sync.c
cp ../../../../kern/vfs_syscalls.c src/kern/vfs_syscalls.c
cp ../../../../kern/vfs_vnops.c src/kern/vfs_vnops.c
cp ../../../../kern/vnode_if.c src/kern/vnode_if.c
mkdir -p src/lib/libkern
cp ../../../../lib/libkern/__main.c src/lib/libkern/__main.c
mkdir -p src/lib/libkern/arch/mips64
cp ../../../../lib/libkern/arch/mips64/DEFS.h src/lib/libkern/arch/mips64/DEFS.h
cp ../../../../lib/libkern/arch/mips64/bcmp.S src/lib/libkern/arch/mips64/bcmp.S
cp ../../../../lib/libkern/arch/mips64/bcopy.S src/lib/libkern/arch/mips64/bcopy.S
cp ../../../../lib/libkern/arch/mips64/bzero.S src/lib/libkern/arch/mips64/bzero.S
cp ../../../../lib/libkern/arch/mips64/ffs.S src/lib/libkern/arch/mips64/ffs.S
cp ../../../../lib/libkern/arch/mips64/htonl.S src/lib/libkern/arch/mips64/htonl.S
cp ../../../../lib/libkern/arch/mips64/htons.S src/lib/libkern/arch/mips64/htons.S
cp ../../../../lib/libkern/arch/mips64/memcpy.S src/lib/libkern/arch/mips64/memcpy.S
cp ../../../../lib/libkern/arch/mips64/memmove.S src/lib/libkern/arch/mips64/memmove.S
cp ../../../../lib/libkern/arch/mips64/ovbcopy.S src/lib/libkern/arch/mips64/ovbcopy.S
cp ../../../../lib/libkern/arch/mips64/strcmp.S src/lib/libkern/arch/mips64/strcmp.S
cp ../../../../lib/libkern/arch/mips64/strlen.S src/lib/libkern/arch/mips64/strlen.S
cp ../../../../lib/libkern/getsn.c src/lib/libkern/getsn.c
cp ../../../../lib/libkern/imax.c src/lib/libkern/imax.c
cp ../../../../lib/libkern/imin.c src/lib/libkern/imin.c
cp ../../../../lib/libkern/libkern.h src/lib/libkern/libkern.h
cp ../../../../lib/libkern/lmax.c src/lib/libkern/lmax.c
cp ../../../../lib/libkern/lmin.c src/lib/libkern/lmin.c
cp ../../../../lib/libkern/max.c src/lib/libkern/max.c
cp ../../../../lib/libkern/memchr.c src/lib/libkern/memchr.c
cp ../../../../lib/libkern/memcmp.c src/lib/libkern/memcmp.c
cp ../../../../lib/libkern/memset.c src/lib/libkern/memset.c
cp ../../../../lib/libkern/min.c src/lib/libkern/min.c
cp ../../../../lib/libkern/random.c src/lib/libkern/random.c
cp ../../../../lib/libkern/scanc.c src/lib/libkern/scanc.c
cp ../../../../lib/libkern/skpc.c src/lib/libkern/skpc.c
cp ../../../../lib/libkern/strchr.c src/lib/libkern/strchr.c
cp ../../../../lib/libkern/strlcat.c src/lib/libkern/strlcat.c
cp ../../../../lib/libkern/strlcpy.c src/lib/libkern/strlcpy.c
cp ../../../../lib/libkern/strncasecmp.c src/lib/libkern/strncasecmp.c
cp ../../../../lib/libkern/strncmp.c src/lib/libkern/strncmp.c
cp ../../../../lib/libkern/strncpy.c src/lib/libkern/strncpy.c
cp ../../../../lib/libkern/strrchr.c src/lib/libkern/strrchr.c
cp ../../../../lib/libkern/ulmax.c src/lib/libkern/ulmax.c
cp ../../../../lib/libkern/ulmin.c src/lib/libkern/ulmin.c
mkdir -p src/miscfs/deadfs
cp ../../../../miscfs/deadfs/dead_vnops.c src/miscfs/deadfs/dead_vnops.c
mkdir -p src/miscfs/fifofs
cp ../../../../miscfs/fifofs/fifo.h src/miscfs/fifofs/fifo.h
cp ../../../../miscfs/fifofs/fifo_vnops.c src/miscfs/fifofs/fifo_vnops.c
mkdir -p src/miscfs/specfs
cp ../../../../miscfs/specfs/spec_subr.c src/miscfs/specfs/spec_subr.c
cp ../../../../miscfs/specfs/spec_vnops.c src/miscfs/specfs/spec_vnops.c
cp ../../../../miscfs/specfs/specdev.h src/miscfs/specfs/specdev.h
mkdir -p src/msdosfs
cp ../../../../msdosfs/bootsect.h src/msdosfs/bootsect.h
cp ../../../../msdosfs/bpb.h src/msdosfs/bpb.h
cp ../../../../msdosfs/denode.h src/msdosfs/denode.h
cp ../../../../msdosfs/direntry.h src/msdosfs/direntry.h
cp ../../../../msdosfs/fat.h src/msdosfs/fat.h
cp ../../../../msdosfs/msdosfs_conv.c src/msdosfs/msdosfs_conv.c
cp ../../../../msdosfs/msdosfs_denode.c src/msdosfs/msdosfs_denode.c
cp ../../../../msdosfs/msdosfs_fat.c src/msdosfs/msdosfs_fat.c
cp ../../../../msdosfs/msdosfs_lookup.c src/msdosfs/msdosfs_lookup.c
cp ../../../../msdosfs/msdosfs_vfsops.c src/msdosfs/msdosfs_vfsops.c
cp ../../../../msdosfs/msdosfs_vnops.c src/msdosfs/msdosfs_vnops.c
cp ../../../../msdosfs/msdosfsmount.h src/msdosfs/msdosfsmount.h
mkdir -p src/net
cp ../../../../net/bpf.c src/net/bpf.c
cp ../../../../net/bpf.h src/net/bpf.h
cp ../../../../net/bpf_filter.c src/net/bpf_filter.c
cp ../../../../net/bpfdesc.h src/net/bpfdesc.h
cp ../../../../net/bridgestp.c src/net/bridgestp.c
cp ../../../../net/bsd-comp.c src/net/bsd-comp.c
cp ../../../../net/ethertypes.h src/net/ethertypes.h
cp ../../../../net/if.c src/net/if.c
cp ../../../../net/if.h src/net/if.h
cp ../../../../net/if_arp.h src/net/if_arp.h
cp ../../../../net/if_bridge.c src/net/if_bridge.c
cp ../../../../net/if_bridge.h src/net/if_bridge.h
cp ../../../../net/if_dl.h src/net/if_dl.h
cp ../../../../net/if_enc.c src/net/if_enc.c
cp ../../../../net/if_enc.h src/net/if_enc.h
cp ../../../../net/if_ethersubr.c src/net/if_ethersubr.c
cp ../../../../net/if_fddi.h src/net/if_fddi.h
cp ../../../../net/if_gif.c src/net/if_gif.c
cp ../../../../net/if_gif.h src/net/if_gif.h
cp ../../../../net/if_gre.c src/net/if_gre.c
cp ../../../../net/if_gre.h src/net/if_gre.h
cp ../../../../net/if_llc.h src/net/if_llc.h
cp ../../../../net/if_loop.c src/net/if_loop.c
cp ../../../../net/if_media.c src/net/if_media.c
cp ../../../../net/if_media.h src/net/if_media.h
cp ../../../../net/if_pflog.c src/net/if_pflog.c
cp ../../../../net/if_pflog.h src/net/if_pflog.h
cp ../../../../net/if_pflow.c src/net/if_pflow.c
cp ../../../../net/if_pflow.h src/net/if_pflow.h
cp ../../../../net/if_pfsync.c src/net/if_pfsync.c
cp ../../../../net/if_pfsync.h src/net/if_pfsync.h
cp ../../../../net/if_ppp.c src/net/if_ppp.c
cp ../../../../net/if_ppp.h src/net/if_ppp.h
cp ../../../../net/if_pppoe.c src/net/if_pppoe.c
cp ../../../../net/if_pppoe.h src/net/if_pppoe.h
cp ../../../../net/if_pppvar.h src/net/if_pppvar.h
cp ../../../../net/if_sl.c src/net/if_sl.c
cp ../../../../net/if_slvar.h src/net/if_slvar.h
cp ../../../../net/if_sppp.h src/net/if_sppp.h
cp ../../../../net/if_spppsubr.c src/net/if_spppsubr.c
cp ../../../../net/if_trunk.c src/net/if_trunk.c
cp ../../../../net/if_trunk.h src/net/if_trunk.h
cp ../../../../net/if_tun.c src/net/if_tun.c
cp ../../../../net/if_tun.h src/net/if_tun.h
cp ../../../../net/if_types.h src/net/if_types.h
cp ../../../../net/if_vether.c src/net/if_vether.c
cp ../../../../net/if_vlan.c src/net/if_vlan.c
cp ../../../../net/if_vlan_var.h src/net/if_vlan_var.h
cp ../../../../net/netisr.h src/net/netisr.h
cp ../../../../net/netisr_dispatch.h src/net/netisr_dispatch.h
cp ../../../../net/pf.c src/net/pf.c
cp ../../../../net/pf_if.c src/net/pf_if.c
cp ../../../../net/pf_ioctl.c src/net/pf_ioctl.c
cp ../../../../net/pf_lb.c src/net/pf_lb.c
cp ../../../../net/pf_norm.c src/net/pf_norm.c
cp ../../../../net/pf_osfp.c src/net/pf_osfp.c
cp ../../../../net/pf_ruleset.c src/net/pf_ruleset.c
cp ../../../../net/pf_table.c src/net/pf_table.c
cp ../../../../net/pfkey.c src/net/pfkey.c
cp ../../../../net/pfkeyv2.c src/net/pfkeyv2.c
cp ../../../../net/pfkeyv2.h src/net/pfkeyv2.h
cp ../../../../net/pfkeyv2_convert.c src/net/pfkeyv2_convert.c
cp ../../../../net/pfkeyv2_parsemessage.c src/net/pfkeyv2_parsemessage.c
cp ../../../../net/pfvar.h src/net/pfvar.h
cp ../../../../net/ppp-comp.h src/net/ppp-comp.h
cp ../../../../net/ppp-deflate.c src/net/ppp-deflate.c
cp ../../../../net/ppp_defs.h src/net/ppp_defs.h
cp ../../../../net/ppp_tty.c src/net/ppp_tty.c
cp ../../../../net/radix.c src/net/radix.c
cp ../../../../net/radix.h src/net/radix.h
cp ../../../../net/radix_mpath.c src/net/radix_mpath.c
cp ../../../../net/radix_mpath.h src/net/radix_mpath.h
cp ../../../../net/raw_cb.c src/net/raw_cb.c
cp ../../../../net/raw_cb.h src/net/raw_cb.h
cp ../../../../net/raw_usrreq.c src/net/raw_usrreq.c
cp ../../../../net/route.c src/net/route.c
cp ../../../../net/route.h src/net/route.h
cp ../../../../net/rtsock.c src/net/rtsock.c
cp ../../../../net/slcompress.c src/net/slcompress.c
cp ../../../../net/slcompress.h src/net/slcompress.h
cp ../../../../net/slip.h src/net/slip.h
cp ../../../../net/trunklacp.c src/net/trunklacp.c
cp ../../../../net/trunklacp.h src/net/trunklacp.h
cp ../../../../net/zlib.c src/net/zlib.c
cp ../../../../net/zlib.h src/net/zlib.h
mkdir -p src/net80211
cp ../../../../net80211/ieee80211.c src/net80211/ieee80211.c
cp ../../../../net80211/ieee80211.h src/net80211/ieee80211.h
cp ../../../../net80211/ieee80211_amrr.c src/net80211/ieee80211_amrr.c
cp ../../../../net80211/ieee80211_amrr.h src/net80211/ieee80211_amrr.h
cp ../../../../net80211/ieee80211_crypto.c src/net80211/ieee80211_crypto.c
cp ../../../../net80211/ieee80211_crypto.h src/net80211/ieee80211_crypto.h
cp ../../../../net80211/ieee80211_crypto_bip.c src/net80211/ieee80211_crypto_bip.c
cp ../../../../net80211/ieee80211_crypto_ccmp.c src/net80211/ieee80211_crypto_ccmp.c
cp ../../../../net80211/ieee80211_crypto_tkip.c src/net80211/ieee80211_crypto_tkip.c
cp ../../../../net80211/ieee80211_crypto_wep.c src/net80211/ieee80211_crypto_wep.c
cp ../../../../net80211/ieee80211_input.c src/net80211/ieee80211_input.c
cp ../../../../net80211/ieee80211_ioctl.c src/net80211/ieee80211_ioctl.c
cp ../../../../net80211/ieee80211_ioctl.h src/net80211/ieee80211_ioctl.h
cp ../../../../net80211/ieee80211_node.c src/net80211/ieee80211_node.c
cp ../../../../net80211/ieee80211_node.h src/net80211/ieee80211_node.h
cp ../../../../net80211/ieee80211_output.c src/net80211/ieee80211_output.c
cp ../../../../net80211/ieee80211_pae_input.c src/net80211/ieee80211_pae_input.c
cp ../../../../net80211/ieee80211_pae_output.c src/net80211/ieee80211_pae_output.c
cp ../../../../net80211/ieee80211_priv.h src/net80211/ieee80211_priv.h
cp ../../../../net80211/ieee80211_proto.c src/net80211/ieee80211_proto.c
cp ../../../../net80211/ieee80211_proto.h src/net80211/ieee80211_proto.h
cp ../../../../net80211/ieee80211_radiotap.h src/net80211/ieee80211_radiotap.h
cp ../../../../net80211/ieee80211_regdomain.c src/net80211/ieee80211_regdomain.c
cp ../../../../net80211/ieee80211_regdomain.h src/net80211/ieee80211_regdomain.h
cp ../../../../net80211/ieee80211_rssadapt.c src/net80211/ieee80211_rssadapt.c
cp ../../../../net80211/ieee80211_rssadapt.h src/net80211/ieee80211_rssadapt.h
cp ../../../../net80211/ieee80211_var.h src/net80211/ieee80211_var.h
mkdir -p src/netinet
cp ../../../../netinet/icmp6.h src/netinet/icmp6.h
cp ../../../../netinet/icmp_var.h src/netinet/icmp_var.h
cp ../../../../netinet/if_ether.c src/netinet/if_ether.c
cp ../../../../netinet/if_ether.h src/netinet/if_ether.h
cp ../../../../netinet/igmp.c src/netinet/igmp.c
cp ../../../../netinet/igmp.h src/netinet/igmp.h
cp ../../../../netinet/igmp_var.h src/netinet/igmp_var.h
cp ../../../../netinet/in.c src/netinet/in.c
cp ../../../../netinet/in.h src/netinet/in.h
cp ../../../../netinet/in4_cksum.c src/netinet/in4_cksum.c
cp ../../../../netinet/in_cksum.c src/netinet/in_cksum.c
cp ../../../../netinet/in_gif.c src/netinet/in_gif.c
cp ../../../../netinet/in_gif.h src/netinet/in_gif.h
cp ../../../../netinet/in_pcb.c src/netinet/in_pcb.c
cp ../../../../netinet/in_pcb.h src/netinet/in_pcb.h
cp ../../../../netinet/in_proto.c src/netinet/in_proto.c
cp ../../../../netinet/in_systm.h src/netinet/in_systm.h
cp ../../../../netinet/in_var.h src/netinet/in_var.h
cp ../../../../netinet/ip.h src/netinet/ip.h
cp ../../../../netinet/ip6.h src/netinet/ip6.h
cp ../../../../netinet/ip_ah.c src/netinet/ip_ah.c
cp ../../../../netinet/ip_ah.h src/netinet/ip_ah.h
cp ../../../../netinet/ip_carp.c src/netinet/ip_carp.c
cp ../../../../netinet/ip_carp.h src/netinet/ip_carp.h
cp ../../../../netinet/ip_divert.c src/netinet/ip_divert.c
cp ../../../../netinet/ip_divert.h src/netinet/ip_divert.h
cp ../../../../netinet/ip_ecn.c src/netinet/ip_ecn.c
cp ../../../../netinet/ip_ecn.h src/netinet/ip_ecn.h
cp ../../../../netinet/ip_esp.c src/netinet/ip_esp.c
cp ../../../../netinet/ip_esp.h src/netinet/ip_esp.h
cp ../../../../netinet/ip_ether.c src/netinet/ip_ether.c
cp ../../../../netinet/ip_ether.h src/netinet/ip_ether.h
cp ../../../../netinet/ip_gre.c src/netinet/ip_gre.c
cp ../../../../netinet/ip_gre.h src/netinet/ip_gre.h
cp ../../../../netinet/ip_icmp.c src/netinet/ip_icmp.c
cp ../../../../netinet/ip_icmp.h src/netinet/ip_icmp.h
cp ../../../../netinet/ip_id.c src/netinet/ip_id.c
cp ../../../../netinet/ip_input.c src/netinet/ip_input.c
cp ../../../../netinet/ip_ipcomp.c src/netinet/ip_ipcomp.c
cp ../../../../netinet/ip_ipcomp.h src/netinet/ip_ipcomp.h
cp ../../../../netinet/ip_ipip.c src/netinet/ip_ipip.c
cp ../../../../netinet/ip_ipip.h src/netinet/ip_ipip.h
cp ../../../../netinet/ip_ipsp.c src/netinet/ip_ipsp.c
cp ../../../../netinet/ip_ipsp.h src/netinet/ip_ipsp.h
cp ../../../../netinet/ip_mroute.c src/netinet/ip_mroute.c
cp ../../../../netinet/ip_mroute.h src/netinet/ip_mroute.h
cp ../../../../netinet/ip_output.c src/netinet/ip_output.c
cp ../../../../netinet/ip_spd.c src/netinet/ip_spd.c
cp ../../../../netinet/ip_var.h src/netinet/ip_var.h
cp ../../../../netinet/ipsec_input.c src/netinet/ipsec_input.c
cp ../../../../netinet/ipsec_output.c src/netinet/ipsec_output.c
cp ../../../../netinet/raw_ip.c src/netinet/raw_ip.c
cp ../../../../netinet/tcp.h src/netinet/tcp.h
cp ../../../../netinet/tcp_debug.c src/netinet/tcp_debug.c
cp ../../../../netinet/tcp_debug.h src/netinet/tcp_debug.h
cp ../../../../netinet/tcp_fsm.h src/netinet/tcp_fsm.h
cp ../../../../netinet/tcp_input.c src/netinet/tcp_input.c
cp ../../../../netinet/tcp_output.c src/netinet/tcp_output.c
cp ../../../../netinet/tcp_seq.h src/netinet/tcp_seq.h
cp ../../../../netinet/tcp_subr.c src/netinet/tcp_subr.c
cp ../../../../netinet/tcp_timer.c src/netinet/tcp_timer.c
cp ../../../../netinet/tcp_timer.h src/netinet/tcp_timer.h
cp ../../../../netinet/tcp_usrreq.c src/netinet/tcp_usrreq.c
cp ../../../../netinet/tcp_var.h src/netinet/tcp_var.h
cp ../../../../netinet/tcpip.h src/netinet/tcpip.h
cp ../../../../netinet/udp.h src/netinet/udp.h
cp ../../../../netinet/udp_usrreq.c src/netinet/udp_usrreq.c
cp ../../../../netinet/udp_var.h src/netinet/udp_var.h
mkdir -p src/netinet6
cp ../../../../netinet6/dest6.c src/netinet6/dest6.c
cp ../../../../netinet6/frag6.c src/netinet6/frag6.c
cp ../../../../netinet6/icmp6.c src/netinet6/icmp6.c
cp ../../../../netinet6/in6.c src/netinet6/in6.c
cp ../../../../netinet6/in6.h src/netinet6/in6.h
cp ../../../../netinet6/in6_cksum.c src/netinet6/in6_cksum.c
cp ../../../../netinet6/in6_gif.c src/netinet6/in6_gif.c
cp ../../../../netinet6/in6_gif.h src/netinet6/in6_gif.h
cp ../../../../netinet6/in6_ifattach.c src/netinet6/in6_ifattach.c
cp ../../../../netinet6/in6_ifattach.h src/netinet6/in6_ifattach.h
cp ../../../../netinet6/in6_pcb.c src/netinet6/in6_pcb.c
cp ../../../../netinet6/in6_proto.c src/netinet6/in6_proto.c
cp ../../../../netinet6/in6_src.c src/netinet6/in6_src.c
cp ../../../../netinet6/in6_var.h src/netinet6/in6_var.h
cp ../../../../netinet6/ip6_divert.c src/netinet6/ip6_divert.c
cp ../../../../netinet6/ip6_divert.h src/netinet6/ip6_divert.h
cp ../../../../netinet6/ip6_forward.c src/netinet6/ip6_forward.c
cp ../../../../netinet6/ip6_id.c src/netinet6/ip6_id.c
cp ../../../../netinet6/ip6_input.c src/netinet6/ip6_input.c
cp ../../../../netinet6/ip6_mroute.c src/netinet6/ip6_mroute.c
cp ../../../../netinet6/ip6_mroute.h src/netinet6/ip6_mroute.h
cp ../../../../netinet6/ip6_output.c src/netinet6/ip6_output.c
cp ../../../../netinet6/ip6_var.h src/netinet6/ip6_var.h
cp ../../../../netinet6/ip6protosw.h src/netinet6/ip6protosw.h
cp ../../../../netinet6/mld6.c src/netinet6/mld6.c
cp ../../../../netinet6/mld6_var.h src/netinet6/mld6_var.h
cp ../../../../netinet6/nd6.c src/netinet6/nd6.c
cp ../../../../netinet6/nd6.h src/netinet6/nd6.h
cp ../../../../netinet6/nd6_nbr.c src/netinet6/nd6_nbr.c
cp ../../../../netinet6/nd6_rtr.c src/netinet6/nd6_rtr.c
cp ../../../../netinet6/pim6.h src/netinet6/pim6.h
cp ../../../../netinet6/pim6_var.h src/netinet6/pim6_var.h
cp ../../../../netinet6/raw_ip6.c src/netinet6/raw_ip6.c
cp ../../../../netinet6/raw_ip6.h src/netinet6/raw_ip6.h
cp ../../../../netinet6/route6.c src/netinet6/route6.c
cp ../../../../netinet6/tcpipv6.h src/netinet6/tcpipv6.h
cp ../../../../netinet6/udp6_output.c src/netinet6/udp6_output.c
mkdir -p src/nfs
cp ../../../../nfs/krpc.h src/nfs/krpc.h
cp ../../../../nfs/krpc_subr.c src/nfs/krpc_subr.c
cp ../../../../nfs/nfs.h src/nfs/nfs.h
cp ../../../../nfs/nfs_bio.c src/nfs/nfs_bio.c
cp ../../../../nfs/nfs_boot.c src/nfs/nfs_boot.c
cp ../../../../nfs/nfs_debug.c src/nfs/nfs_debug.c
cp ../../../../nfs/nfs_kq.c src/nfs/nfs_kq.c
cp ../../../../nfs/nfs_node.c src/nfs/nfs_node.c
cp ../../../../nfs/nfs_serv.c src/nfs/nfs_serv.c
cp ../../../../nfs/nfs_socket.c src/nfs/nfs_socket.c
cp ../../../../nfs/nfs_srvcache.c src/nfs/nfs_srvcache.c
cp ../../../../nfs/nfs_subs.c src/nfs/nfs_subs.c
cp ../../../../nfs/nfs_syscalls.c src/nfs/nfs_syscalls.c
cp ../../../../nfs/nfs_var.h src/nfs/nfs_var.h
cp ../../../../nfs/nfs_vfsops.c src/nfs/nfs_vfsops.c
cp ../../../../nfs/nfs_vnops.c src/nfs/nfs_vnops.c
cp ../../../../nfs/nfsdiskless.h src/nfs/nfsdiskless.h
cp ../../../../nfs/nfsm_subs.h src/nfs/nfsm_subs.h
cp ../../../../nfs/nfsmount.h src/nfs/nfsmount.h
cp ../../../../nfs/nfsnode.h src/nfs/nfsnode.h
cp ../../../../nfs/nfsproto.h src/nfs/nfsproto.h
cp ../../../../nfs/nfsrvcache.h src/nfs/nfsrvcache.h
cp ../../../../nfs/rpcv2.h src/nfs/rpcv2.h
cp ../../../../nfs/xdr_subs.h src/nfs/xdr_subs.h
mkdir -p src/nnpfs
cp ../../../../nnpfs/afssysdefs.h src/nnpfs/afssysdefs.h
cp ../../../../nnpfs/nnnpfs.h src/nnpfs/nnnpfs.h
cp ../../../../nnpfs/nnpfs_attr.h src/nnpfs/nnpfs_attr.h
cp ../../../../nnpfs/nnpfs_common-bsd.c src/nnpfs/nnpfs_common-bsd.c
cp ../../../../nnpfs/nnpfs_common.h src/nnpfs/nnpfs_common.h
cp ../../../../nnpfs/nnpfs_config.h src/nnpfs/nnpfs_config.h
cp ../../../../nnpfs/nnpfs_deb.c src/nnpfs/nnpfs_deb.c
cp ../../../../nnpfs/nnpfs_deb.h src/nnpfs/nnpfs_deb.h
cp ../../../../nnpfs/nnpfs_debug.h src/nnpfs/nnpfs_debug.h
cp ../../../../nnpfs/nnpfs_dev-bsd.c src/nnpfs/nnpfs_dev-bsd.c
cp ../../../../nnpfs/nnpfs_dev-common.c src/nnpfs/nnpfs_dev-common.c
cp ../../../../nnpfs/nnpfs_dev.h src/nnpfs/nnpfs_dev.h
cp ../../../../nnpfs/nnpfs_fs.h src/nnpfs/nnpfs_fs.h
cp ../../../../nnpfs/nnpfs_locl.h src/nnpfs/nnpfs_locl.h
cp ../../../../nnpfs/nnpfs_message.c src/nnpfs/nnpfs_message.c
cp ../../../../nnpfs/nnpfs_message.h src/nnpfs/nnpfs_message.h
cp ../../../../nnpfs/nnpfs_msg_locl.h src/nnpfs/nnpfs_msg_locl.h
cp ../../../../nnpfs/nnpfs_node-bsd.c src/nnpfs/nnpfs_node-bsd.c
cp ../../../../nnpfs/nnpfs_node.c src/nnpfs/nnpfs_node.c
cp ../../../../nnpfs/nnpfs_node.h src/nnpfs/nnpfs_node.h
cp ../../../../nnpfs/nnpfs_pioctl.h src/nnpfs/nnpfs_pioctl.h
cp ../../../../nnpfs/nnpfs_queue.h src/nnpfs/nnpfs_queue.h
cp ../../../../nnpfs/nnpfs_syscalls-common.c src/nnpfs/nnpfs_syscalls-common.c
cp ../../../../nnpfs/nnpfs_syscalls.h src/nnpfs/nnpfs_syscalls.h
cp ../../../../nnpfs/nnpfs_vfsops-bsd.c src/nnpfs/nnpfs_vfsops-bsd.c
cp ../../../../nnpfs/nnpfs_vfsops-bsd.h src/nnpfs/nnpfs_vfsops-bsd.h
cp ../../../../nnpfs/nnpfs_vfsops-common.c src/nnpfs/nnpfs_vfsops-common.c
cp ../../../../nnpfs/nnpfs_vfsops-openbsd.c src/nnpfs/nnpfs_vfsops-openbsd.c
cp ../../../../nnpfs/nnpfs_vfsops.h src/nnpfs/nnpfs_vfsops.h
cp ../../../../nnpfs/nnpfs_vnodeops-bsd.c src/nnpfs/nnpfs_vnodeops-bsd.c
cp ../../../../nnpfs/nnpfs_vnodeops-common.c src/nnpfs/nnpfs_vnodeops-common.c
cp ../../../../nnpfs/nnpfs_vnodeops.h src/nnpfs/nnpfs_vnodeops.h
cp ../../../../nnpfs/nnpfs_vopdefs.h src/nnpfs/nnpfs_vopdefs.h
mkdir -p src/scsi
cp ../../../../scsi/cd.c src/scsi/cd.c
cp ../../../../scsi/cd.h src/scsi/cd.h
cp ../../../../scsi/ch.c src/scsi/ch.c
cp ../../../../scsi/scsi_all.h src/scsi/scsi_all.h
cp ../../../../scsi/scsi_base.c src/scsi/scsi_base.c
cp ../../../../scsi/scsi_changer.h src/scsi/scsi_changer.h
cp ../../../../scsi/scsi_debug.h src/scsi/scsi_debug.h
cp ../../../../scsi/scsi_disk.h src/scsi/scsi_disk.h
cp ../../../../scsi/scsi_ioctl.c src/scsi/scsi_ioctl.c
cp ../../../../scsi/scsi_scanner.h src/scsi/scsi_scanner.h
cp ../../../../scsi/scsi_tape.h src/scsi/scsi_tape.h
cp ../../../../scsi/scsiconf.c src/scsi/scsiconf.c
cp ../../../../scsi/scsiconf.h src/scsi/scsiconf.h
cp ../../../../scsi/sd.c src/scsi/sd.c
cp ../../../../scsi/sdvar.h src/scsi/sdvar.h
cp ../../../../scsi/ss.c src/scsi/ss.c
cp ../../../../scsi/ss_mustek.c src/scsi/ss_mustek.c
cp ../../../../scsi/ss_mustek.h src/scsi/ss_mustek.h
cp ../../../../scsi/ss_scanjet.c src/scsi/ss_scanjet.c
cp ../../../../scsi/ssvar.h src/scsi/ssvar.h
cp ../../../../scsi/st.c src/scsi/st.c
cp ../../../../scsi/uk.c src/scsi/uk.c
mkdir -p src/sys
cp ../../../../sys/_types.h src/sys/_types.h
cp ../../../../sys/acct.h src/sys/acct.h
cp ../../../../sys/ataio.h src/sys/ataio.h
cp ../../../../sys/buf.h src/sys/buf.h
cp ../../../../sys/cdefs.h src/sys/cdefs.h
cp ../../../../sys/cdio.h src/sys/cdio.h
cp ../../../../sys/chio.h src/sys/chio.h
cp ../../../../sys/conf.h src/sys/conf.h
cp ../../../../sys/core.h src/sys/core.h
cp ../../../../sys/device.h src/sys/device.h
cp ../../../../sys/dirent.h src/sys/dirent.h
cp ../../../../sys/disk.h src/sys/disk.h
cp ../../../../sys/disklabel.h src/sys/disklabel.h
cp ../../../../sys/dkio.h src/sys/dkio.h
cp ../../../../sys/dkstat.h src/sys/dkstat.h
cp ../../../../sys/domain.h src/sys/domain.h
cp ../../../../sys/endian.h src/sys/endian.h
cp ../../../../sys/errno.h src/sys/errno.h
cp ../../../../sys/evcount.h src/sys/evcount.h
cp ../../../../sys/event.h src/sys/event.h
cp ../../../../sys/eventvar.h src/sys/eventvar.h
cp ../../../../sys/exec.h src/sys/exec.h
cp ../../../../sys/exec_aout.h src/sys/exec_aout.h
cp ../../../../sys/exec_elf.h src/sys/exec_elf.h
cp ../../../../sys/exec_olf.h src/sys/exec_olf.h
cp ../../../../sys/exec_script.h src/sys/exec_script.h
cp ../../../../sys/extent.h src/sys/extent.h
cp ../../../../sys/fcntl.h src/sys/fcntl.h
cp ../../../../sys/file.h src/sys/file.h
cp ../../../../sys/filedesc.h src/sys/filedesc.h
cp ../../../../sys/filio.h src/sys/filio.h
cp ../../../../sys/gpio.h src/sys/gpio.h
cp ../../../../sys/hash.h src/sys/hash.h
cp ../../../../sys/hotplug.h src/sys/hotplug.h
cp ../../../../sys/ioccom.h src/sys/ioccom.h
cp ../../../../sys/ioctl.h src/sys/ioctl.h
cp ../../../../sys/ioctl_compat.h src/sys/ioctl_compat.h
cp ../../../../sys/ipc.h src/sys/ipc.h
cp ../../../../sys/kernel.h src/sys/kernel.h
cp ../../../../sys/kthread.h src/sys/kthread.h
cp ../../../../sys/ktrace.h src/sys/ktrace.h
cp ../../../../sys/limits.h src/sys/limits.h
cp ../../../../sys/lkm.h src/sys/lkm.h
cp ../../../../sys/lock.h src/sys/lock.h
cp ../../../../sys/lockf.h src/sys/lockf.h
cp ../../../../sys/malloc.h src/sys/malloc.h
cp ../../../../sys/mbuf.h src/sys/mbuf.h
cp ../../../../sys/mman.h src/sys/mman.h
cp ../../../../sys/mount.h src/sys/mount.h
cp ../../../../sys/msg.h src/sys/msg.h
cp ../../../../sys/msgbuf.h src/sys/msgbuf.h
cp ../../../../sys/mtio.h src/sys/mtio.h
cp ../../../../sys/mutex.h src/sys/mutex.h
cp ../../../../sys/namei.h src/sys/namei.h
cp ../../../../sys/param.h src/sys/param.h
cp ../../../../sys/pciio.h src/sys/pciio.h
cp ../../../../sys/pipe.h src/sys/pipe.h
cp ../../../../sys/poll.h src/sys/poll.h
cp ../../../../sys/pool.h src/sys/pool.h
cp ../../../../sys/proc.h src/sys/proc.h
cp ../../../../sys/protosw.h src/sys/protosw.h
cp ../../../../sys/ptrace.h src/sys/ptrace.h
cp ../../../../sys/queue.h src/sys/queue.h
cp ../../../../sys/reboot.h src/sys/reboot.h
cp ../../../../sys/resource.h src/sys/resource.h
cp ../../../../sys/resourcevar.h src/sys/resourcevar.h
cp ../../../../sys/rwlock.h src/sys/rwlock.h
cp ../../../../sys/scanio.h src/sys/scanio.h
cp ../../../../sys/sched.h src/sys/sched.h
cp ../../../../sys/scsiio.h src/sys/scsiio.h
cp ../../../../sys/select.h src/sys/select.h
cp ../../../../sys/selinfo.h src/sys/selinfo.h
cp ../../../../sys/sem.h src/sys/sem.h
cp ../../../../sys/sensors.h src/sys/sensors.h
cp ../../../../sys/shm.h src/sys/shm.h
cp ../../../../sys/siginfo.h src/sys/siginfo.h
cp ../../../../sys/signal.h src/sys/signal.h
cp ../../../../sys/signalvar.h src/sys/signalvar.h
cp ../../../../sys/simplelock.h src/sys/simplelock.h
cp ../../../../sys/socket.h src/sys/socket.h
cp ../../../../sys/socketvar.h src/sys/socketvar.h
cp ../../../../sys/sockio.h src/sys/sockio.h
cp ../../../../sys/stat.h src/sys/stat.h
cp ../../../../sys/stdarg.h src/sys/stdarg.h
cp ../../../../sys/stdint.h src/sys/stdint.h
cp ../../../../sys/swap.h src/sys/swap.h
cp ../../../../sys/syscall.h src/sys/syscall.h
cp ../../../../sys/syscallargs.h src/sys/syscallargs.h
cp ../../../../sys/sysctl.h src/sys/sysctl.h
cp ../../../../sys/syslimits.h src/sys/syslimits.h
cp ../../../../sys/syslog.h src/sys/syslog.h
cp ../../../../sys/systm.h src/sys/systm.h
cp ../../../../sys/termios.h src/sys/termios.h
cp ../../../../sys/time.h src/sys/time.h
cp ../../../../sys/timeb.h src/sys/timeb.h
cp ../../../../sys/timeout.h src/sys/timeout.h
cp ../../../../sys/times.h src/sys/times.h
cp ../../../../sys/timetc.h src/sys/timetc.h
cp ../../../../sys/tprintf.h src/sys/tprintf.h
cp ../../../../sys/tree.h src/sys/tree.h
cp ../../../../sys/tty.h src/sys/tty.h
cp ../../../../sys/ttychars.h src/sys/ttychars.h
cp ../../../../sys/ttycom.h src/sys/ttycom.h
cp ../../../../sys/ttydefaults.h src/sys/ttydefaults.h
cp ../../../../sys/ttydev.h src/sys/ttydev.h
cp ../../../../sys/types.h src/sys/types.h
cp ../../../../sys/ucred.h src/sys/ucred.h
cp ../../../../sys/uio.h src/sys/uio.h
cp ../../../../sys/un.h src/sys/un.h
cp ../../../../sys/unistd.h src/sys/unistd.h
cp ../../../../sys/unpcb.h src/sys/unpcb.h
cp ../../../../sys/user.h src/sys/user.h
cp ../../../../sys/utsname.h src/sys/utsname.h
cp ../../../../sys/videoio.h src/sys/videoio.h
cp ../../../../sys/vmmeter.h src/sys/vmmeter.h
cp ../../../../sys/vnode.h src/sys/vnode.h
cp ../../../../sys/vnode_if.h src/sys/vnode_if.h
cp ../../../../sys/wait.h src/sys/wait.h
cp ../../../../sys/workq.h src/sys/workq.h
mkdir -p src/ufs/ext2fs
cp ../../../../ufs/ext2fs/ext2fs.h src/ufs/ext2fs/ext2fs.h
cp ../../../../ufs/ext2fs/ext2fs_alloc.c src/ufs/ext2fs/ext2fs_alloc.c
cp ../../../../ufs/ext2fs/ext2fs_balloc.c src/ufs/ext2fs/ext2fs_balloc.c
cp ../../../../ufs/ext2fs/ext2fs_bmap.c src/ufs/ext2fs/ext2fs_bmap.c
cp ../../../../ufs/ext2fs/ext2fs_bswap.c src/ufs/ext2fs/ext2fs_bswap.c
cp ../../../../ufs/ext2fs/ext2fs_dinode.h src/ufs/ext2fs/ext2fs_dinode.h
cp ../../../../ufs/ext2fs/ext2fs_dir.h src/ufs/ext2fs/ext2fs_dir.h
cp ../../../../ufs/ext2fs/ext2fs_extern.h src/ufs/ext2fs/ext2fs_extern.h
cp ../../../../ufs/ext2fs/ext2fs_inode.c src/ufs/ext2fs/ext2fs_inode.c
cp ../../../../ufs/ext2fs/ext2fs_lookup.c src/ufs/ext2fs/ext2fs_lookup.c
cp ../../../../ufs/ext2fs/ext2fs_readwrite.c src/ufs/ext2fs/ext2fs_readwrite.c
cp ../../../../ufs/ext2fs/ext2fs_subr.c src/ufs/ext2fs/ext2fs_subr.c
cp ../../../../ufs/ext2fs/ext2fs_vfsops.c src/ufs/ext2fs/ext2fs_vfsops.c
cp ../../../../ufs/ext2fs/ext2fs_vnops.c src/ufs/ext2fs/ext2fs_vnops.c
mkdir -p src/ufs/ffs
cp ../../../../ufs/ffs/ffs_alloc.c src/ufs/ffs/ffs_alloc.c
cp ../../../../ufs/ffs/ffs_balloc.c src/ufs/ffs/ffs_balloc.c
cp ../../../../ufs/ffs/ffs_extern.h src/ufs/ffs/ffs_extern.h
cp ../../../../ufs/ffs/ffs_inode.c src/ufs/ffs/ffs_inode.c
cp ../../../../ufs/ffs/ffs_softdep.c src/ufs/ffs/ffs_softdep.c
cp ../../../../ufs/ffs/ffs_softdep_stub.c src/ufs/ffs/ffs_softdep_stub.c
cp ../../../../ufs/ffs/ffs_subr.c src/ufs/ffs/ffs_subr.c
cp ../../../../ufs/ffs/ffs_tables.c src/ufs/ffs/ffs_tables.c
cp ../../../../ufs/ffs/ffs_vfsops.c src/ufs/ffs/ffs_vfsops.c
cp ../../../../ufs/ffs/ffs_vnops.c src/ufs/ffs/ffs_vnops.c
cp ../../../../ufs/ffs/fs.h src/ufs/ffs/fs.h
cp ../../../../ufs/ffs/softdep.h src/ufs/ffs/softdep.h
mkdir -p src/ufs/mfs
cp ../../../../ufs/mfs/mfs_extern.h src/ufs/mfs/mfs_extern.h
cp ../../../../ufs/mfs/mfs_vfsops.c src/ufs/mfs/mfs_vfsops.c
cp ../../../../ufs/mfs/mfs_vnops.c src/ufs/mfs/mfs_vnops.c
cp ../../../../ufs/mfs/mfsnode.h src/ufs/mfs/mfsnode.h
mkdir -p src/ufs/ufs
cp ../../../../ufs/ufs/dinode.h src/ufs/ufs/dinode.h
cp ../../../../ufs/ufs/dir.h src/ufs/ufs/dir.h
cp ../../../../ufs/ufs/dirhash.h src/ufs/ufs/dirhash.h
cp ../../../../ufs/ufs/inode.h src/ufs/ufs/inode.h
cp ../../../../ufs/ufs/quota.h src/ufs/ufs/quota.h
cp ../../../../ufs/ufs/ufs_bmap.c src/ufs/ufs/ufs_bmap.c
cp ../../../../ufs/ufs/ufs_dirhash.c src/ufs/ufs/ufs_dirhash.c
cp ../../../../ufs/ufs/ufs_extern.h src/ufs/ufs/ufs_extern.h
cp ../../../../ufs/ufs/ufs_ihash.c src/ufs/ufs/ufs_ihash.c
cp ../../../../ufs/ufs/ufs_inode.c src/ufs/ufs/ufs_inode.c
cp ../../../../ufs/ufs/ufs_lookup.c src/ufs/ufs/ufs_lookup.c
cp ../../../../ufs/ufs/ufs_quota.c src/ufs/ufs/ufs_quota.c
cp ../../../../ufs/ufs/ufs_quota_stub.c src/ufs/ufs/ufs_quota_stub.c
cp ../../../../ufs/ufs/ufs_vfsops.c src/ufs/ufs/ufs_vfsops.c
cp ../../../../ufs/ufs/ufs_vnops.c src/ufs/ufs/ufs_vnops.c
cp ../../../../ufs/ufs/ufsmount.h src/ufs/ufs/ufsmount.h
mkdir -p src/uvm
cp ../../../../uvm/uvm.h src/uvm/uvm.h
cp ../../../../uvm/uvm_amap.c src/uvm/uvm_amap.c
cp ../../../../uvm/uvm_amap.h src/uvm/uvm_amap.h
cp ../../../../uvm/uvm_anon.c src/uvm/uvm_anon.c
cp ../../../../uvm/uvm_anon.h src/uvm/uvm_anon.h
cp ../../../../uvm/uvm_aobj.c src/uvm/uvm_aobj.c
cp ../../../../uvm/uvm_aobj.h src/uvm/uvm_aobj.h
cp ../../../../uvm/uvm_ddb.h src/uvm/uvm_ddb.h
cp ../../../../uvm/uvm_device.c src/uvm/uvm_device.c
cp ../../../../uvm/uvm_device.h src/uvm/uvm_device.h
cp ../../../../uvm/uvm_extern.h src/uvm/uvm_extern.h
cp ../../../../uvm/uvm_fault.c src/uvm/uvm_fault.c
cp ../../../../uvm/uvm_fault.h src/uvm/uvm_fault.h
cp ../../../../uvm/uvm_glue.c src/uvm/uvm_glue.c
cp ../../../../uvm/uvm_glue.h src/uvm/uvm_glue.h
cp ../../../../uvm/uvm_init.c src/uvm/uvm_init.c
cp ../../../../uvm/uvm_io.c src/uvm/uvm_io.c
cp ../../../../uvm/uvm_km.c src/uvm/uvm_km.c
cp ../../../../uvm/uvm_km.h src/uvm/uvm_km.h
cp ../../../../uvm/uvm_loan.h src/uvm/uvm_loan.h
cp ../../../../uvm/uvm_map.c src/uvm/uvm_map.c
cp ../../../../uvm/uvm_map.h src/uvm/uvm_map.h
cp ../../../../uvm/uvm_meter.c src/uvm/uvm_meter.c
cp ../../../../uvm/uvm_mmap.c src/uvm/uvm_mmap.c
cp ../../../../uvm/uvm_object.c src/uvm/uvm_object.c
cp ../../../../uvm/uvm_object.h src/uvm/uvm_object.h
cp ../../../../uvm/uvm_page.c src/uvm/uvm_page.c
cp ../../../../uvm/uvm_page.h src/uvm/uvm_page.h
cp ../../../../uvm/uvm_pager.c src/uvm/uvm_pager.c
cp ../../../../uvm/uvm_pager.h src/uvm/uvm_pager.h
cp ../../../../uvm/uvm_param.h src/uvm/uvm_param.h
cp ../../../../uvm/uvm_pdaemon.c src/uvm/uvm_pdaemon.c
cp ../../../../uvm/uvm_pdaemon.h src/uvm/uvm_pdaemon.h
cp ../../../../uvm/uvm_pglist.c src/uvm/uvm_pglist.c
cp ../../../../uvm/uvm_pglist.h src/uvm/uvm_pglist.h
cp ../../../../uvm/uvm_pmap.h src/uvm/uvm_pmap.h
cp ../../../../uvm/uvm_stat.c src/uvm/uvm_stat.c
cp ../../../../uvm/uvm_stat.h src/uvm/uvm_stat.h
cp ../../../../uvm/uvm_swap.c src/uvm/uvm_swap.c
cp ../../../../uvm/uvm_swap.h src/uvm/uvm_swap.h
cp ../../../../uvm/uvm_swap_encrypt.c src/uvm/uvm_swap_encrypt.c
cp ../../../../uvm/uvm_swap_encrypt.h src/uvm/uvm_swap_encrypt.h
cp ../../../../uvm/uvm_unix.c src/uvm/uvm_unix.c
cp ../../../../uvm/uvm_user.c src/uvm/uvm_user.c
cp ../../../../uvm/uvm_vnode.c src/uvm/uvm_vnode.c
cp ../../../../uvm/uvm_vnode.h src/uvm/uvm_vnode.h
mkdir -p include
cp assym.h include/assym.h
cp atapiscsi.h include/atapiscsi.h
cp audio.h include/audio.h
cp bio.h include/bio.h
cp bluetooth.h include/bluetooth.h
cp bpfilter.h include/bpfilter.h
cp bridge.h include/bridge.h
cp carp.h include/carp.h
cp ccd.h include/ccd.h
cp cd.h include/cd.h
cp ch.h include/ch.h
cp com.h include/com.h
cp ehci.h include/ehci.h
cp enc.h include/enc.h
cp endrun.h include/endrun.h
cp ether.h include/ether.h
cp faith.h include/faith.h
cp gif.h include/gif.h
cp gpio.h include/gpio.h
cp gre.h include/gre.h
cp hotplug.h include/hotplug.h
cp inet.h include/inet.h
mkdir -p src
cp ioconf.c src/ioconf.c
cp isa.h include/isa.h
cp isadma.h include/isadma.h
cp isapnp.h include/isapnp.h
cp ksyms.h include/ksyms.h
cp lpt.h include/lpt.h
mkdir -p include/machine
cp machine/_types.h include/machine/_types.h
cp machine/asm.h include/machine/asm.h
cp machine/atomic.h include/machine/atomic.h
cp machine/autoconf.h include/machine/autoconf.h
cp machine/bus.h include/machine/bus.h
cp machine/cdefs.h include/machine/cdefs.h
cp machine/cpu.h include/machine/cpu.h
cp machine/cpustate.h include/machine/cpustate.h
cp machine/db_machdep.h include/machine/db_machdep.h
cp machine/disklabel.h include/machine/disklabel.h
cp machine/endian.h include/machine/endian.h
cp machine/exec.h include/machine/exec.h
cp machine/frame.h include/machine/frame.h
cp machine/internal_types.h include/machine/internal_types.h
cp machine/intr.h include/machine/intr.h
cp machine/isa_machdep.h include/machine/isa_machdep.h
cp machine/limits.h include/machine/limits.h
cp machine/lock.h include/machine/lock.h
cp machine/loongson2.h include/machine/loongson2.h
cp machine/memconf.h include/machine/memconf.h
cp machine/mips_opcode.h include/machine/mips_opcode.h
cp machine/mutex.h include/machine/mutex.h
cp machine/param.h include/machine/param.h
cp machine/pcb.h include/machine/pcb.h
cp machine/pci_machdep.h include/machine/pci_machdep.h
cp machine/pmap.h include/machine/pmap.h
cp machine/pmon.h include/machine/pmon.h
cp machine/proc.h include/machine/proc.h
cp machine/pte.h include/machine/pte.h
cp machine/ptrace.h include/machine/ptrace.h
cp machine/reg.h include/machine/reg.h
cp machine/regdef.h include/machine/regdef.h
cp machine/regnum.h include/machine/regnum.h
cp machine/signal.h include/machine/signal.h
cp machine/spinlock.h include/machine/spinlock.h
cp machine/trap.h include/machine/trap.h
cp machine/vmparam.h include/machine/vmparam.h
mkdir -p include/mips64
cp mips64/_types.h include/mips64/_types.h
cp mips64/archtype.h include/mips64/archtype.h
cp mips64/asm.h include/mips64/asm.h
cp mips64/atomic.h include/mips64/atomic.h
cp mips64/cdefs.h include/mips64/cdefs.h
cp mips64/cpu.h include/mips64/cpu.h
cp mips64/cpustate.h include/mips64/cpustate.h
cp mips64/db_machdep.h include/mips64/db_machdep.h
cp mips64/endian.h include/mips64/endian.h
cp mips64/exec.h include/mips64/exec.h
cp mips64/frame.h include/mips64/frame.h
cp mips64/internal_types.h include/mips64/internal_types.h
cp mips64/limits.h include/mips64/limits.h
cp mips64/lock.h include/mips64/lock.h
cp mips64/loongson2.h include/mips64/loongson2.h
cp mips64/memconf.h include/mips64/memconf.h
cp mips64/mips_opcode.h include/mips64/mips_opcode.h
cp mips64/param.h include/mips64/param.h
cp mips64/pcb.h include/mips64/pcb.h
cp mips64/pmap.h include/mips64/pmap.h
cp mips64/proc.h include/mips64/proc.h
cp mips64/pte.h include/mips64/pte.h
cp mips64/ptrace.h include/mips64/ptrace.h
cp mips64/reg.h include/mips64/reg.h
cp mips64/regdef.h include/mips64/regdef.h
cp mips64/regnum.h include/mips64/regnum.h
cp mips64/rm7000.h include/mips64/rm7000.h
cp mips64/signal.h include/mips64/signal.h
cp mips64/spinlock.h include/mips64/spinlock.h
cp mips64/sysarch.h include/mips64/sysarch.h
cp mips64/trap.h include/mips64/trap.h
cp mips64/vmparam.h include/mips64/vmparam.h
cp mpath.h include/mpath.h
cp msts.h include/msts.h
cp nmea.h include/nmea.h
cp ohci.h include/ohci.h
cp param.c src/param.c
cp pci.h include/pci.h
cp pckbc.h include/pckbc.h
cp pckbd.h include/pckbd.h
cp pf.h include/pf.h
cp pflog.h include/pflog.h
cp pflow.h include/pflow.h
cp pfsync.h include/pfsync.h
cp ppp.h include/ppp.h
cp pppoe.h include/pppoe.h
cp pty.h include/pty.h
cp rasops_glue.h include/rasops_glue.h
cp rd.h include/rd.h
cp sd.h include/sd.h
cp sl.h include/sl.h
cp smfb.h include/smfb.h
cp softraid.h include/softraid.h
cp ss.h include/ss.h
cp st.h include/st.h
cp systrace.h include/systrace.h
cp trunk.h include/trunk.h
cp tun.h include/tun.h
cp ucom.h include/ucom.h
cp ugen.h include/ugen.h
cp uhci.h include/uhci.h
cp uhid.h include/uhid.h
cp uk.h include/uk.h
cp ulpt.h include/ulpt.h
cp urio.h include/urio.h
cp usb.h include/usb.h
cp vether.h include/vether.h
cp video.h include/video.h
cp vlan.h include/vlan.h
cp vnd.h include/vnd.h
cp vscsi.h include/vscsi.h
cp wd.h include/wd.h
cp wsdisplay.h include/wsdisplay.h
cp wsfont_glue.h include/wsfont_glue.h
cp wskbd.h include/wskbd.h
cp wsmouse.h include/wsmouse.h
cp wsmux.h include/wsmux.h
